### PR TITLE
SIITBX-357 update tests 

### PR DESCRIPTION
**Pull request by Florian1209**
update the tests input or results due to additionnal tiepointgrids in the SNAP S2 products

### CODE REVIEW

**Comment by Florian1209** [comment]
@oanahogoiu The PR status is Work In Progress.
Could you look the update of CSRO Test (Kompsat and other on going)

**Comment by oanahogoiu** [comment]
What is the purpose of tiePointGrids input parameter with empty value ("tiePointGrids": "")?
Is there a difference between not having at all this input parameter declared in the test and declaring it with empty value?, 
The corresponding xml element from the graph can be let empty, therefore no need to add the empty input parameter. (if the intention was to have it empty)

**Comment by Florian1209** [comment]
Yes, it possible to remove tiepointgrids parameter of the graphReadMultilevel.

**Comment by Florian1209** [comment]
The tests are OK.

**Review by oanahogoiu — APPROVED** [review]
Ok, let's see the effect on Jenkins.

**Pull request merged**
